CREATE TABLE IF NOT EXISTS comments(
    id serial PRIMARY KEY,
    body LONGTEXT NULL,
    movie_id BIGINT(20) UNSIGNED NOT NULL,
    user_id BIGINT(20) UNSIGNED NOT NULL,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE comments ADD CONSTRAINT users_id_comments_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE comments ADD CONSTRAINT movies_id_comments_movie_id_fk FOREIGN KEY (movie_id) REFERENCES movies(id);