version: '3'
services: 
  app:
    build: 
      context: ""
      dockerfile: Dockerfile-go-dev
    container_name: MyPIPE-go
    tty: true
    volumes:
      - ./go:/go
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  
  mysql:
    image:  mysql:latest
    container_name: MyPIPE-mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mypipe
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  nginx:
    build: 
      context: ""
      dockerfile: Dockerfile-nginx-dev
    container_name: MyPIPE-nginx
    tty: true
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
