FROM golang:latest
WORKDIR /go/src/MyPIPE
ADD ./go /go
EXPOSE 8080
ENV Dialect="mysql"
ENV DBName="mypipe"
ENV AWS_REGION="ap-northeast-1"
ENV DBProtocol="tcp(MyPIPE-mysql)"
CMD ["go","build"]
CMD ["./MyPIPE"]