FROM golang:latest
WORKDIR /go/src/MyPIPE
ADD ./go /go
EXPOSE 8080
RUN go build
RUN apt-get update && apt-get upgrade -y && apt-get install -y curl gnupg2 vim && curl -L https://github.com/golang-migrate/migrate/releases/download/v4.11.0/migrate.linux-amd64.tar.gz | tar xvz && mv ./migrate.linux-amd64 /usr/bin/migrate
RUN chmod 755 /go/src/MyPIPE/run.sh
CMD ["/go/src/MyPIPE/run.sh"]