// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase/ChangeThumbnail.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	usecase "MyPIPE/usecase"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIChangeThumbnail is a mock of IChangeThumbnail interface
type MockIChangeThumbnail struct {
	ctrl     *gomock.Controller
	recorder *MockIChangeThumbnailMockRecorder
}

// MockIChangeThumbnailMockRecorder is the mock recorder for MockIChangeThumbnail
type MockIChangeThumbnailMockRecorder struct {
	mock *MockIChangeThumbnail
}

// NewMockIChangeThumbnail creates a new mock instance
func NewMockIChangeThumbnail(ctrl *gomock.Controller) *MockIChangeThumbnail {
	mock := &MockIChangeThumbnail{ctrl: ctrl}
	mock.recorder = &MockIChangeThumbnailMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIChangeThumbnail) EXPECT() *MockIChangeThumbnailMockRecorder {
	return m.recorder
}

// ChangeThumbnail mocks base method
func (m *MockIChangeThumbnail) ChangeThumbnail(changeThumbnailDTO usecase.ChangeThumbnailDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeThumbnail", changeThumbnailDTO)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeThumbnail indicates an expected call of ChangeThumbnail
func (mr *MockIChangeThumbnailMockRecorder) ChangeThumbnail(changeThumbnailDTO interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeThumbnail", reflect.TypeOf((*MockIChangeThumbnail)(nil).ChangeThumbnail), changeThumbnailDTO)
}
