openapi: 3.0.0
info:
  title: UserRegister
  version: '1.0'
  description: ユーザーの本登録
servers:
  - url: 'http://localhost:3000'
paths:
  /register:
    post:
      summary: newUser
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: object
                    properties:
                      user_birthday:
                        type: string
                      user_name:
                        type: string
                      user_password:
                        type: string
                  result:
                    type: string
                  message:
                    type: string
              examples:
                success:
                  value:
                    message: Temporary Registered!
                invalid message:
                  value:
                    messages:
                      user_birthday: cannot be blank
                      user_name: cannot be blank
                      user_password: cannot be blank
                    result: Validation Error
      operationId: post-register
      description: 仮登録済みユーザーの本登録
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
                birthday:
                  type: string
            examples:
              example-1:
                value:
                  name: taro@example.jp
                  password: mypassword123
                  birthday: '1990-08-01'
components:
  schemas: {}
